spring.application.name=back-freelaflow
spring.datasource.url=${URL_CONNECTION}
spring.datasource.driver-class-name=${DRIVER_NAME}
spring.datasource.username=${DBUSER}
spring.datasource.password=${DBPWD}

spring.jpa.database-platform=${DBDIALECT}
spring.jpa.show-sql=${DEBUGQUERY}

spring.mail.host=${HOSTMAIL}
spring.mail.port=${PORTMAIL}
spring.mail.username=${USERMAIL}
spring.mail.password=${PWDMAIL}
spring.mail.properties.mail.smtp.auth=${AUTHMAIL}
spring.mail.properties.mail.smtp.starttls.enable=${TLSMAIL}